"use client";
import { useEffect, useState } from "react";
import { getSupabase } from "@/lib/supabase";
import type { Home } from "@/lib/types";
const kinds = [{id:'home',label:'自宅'},{id:'parents',label:'実家'},{id:'second',label:'別宅'},{id:'rental',label:'賃貸'}] as const;
export function HomeControls({ home, cloud, busy, canDelete, onCreate, onUpdate, onDelete, onRefresh }: { home: Home; cloud: boolean; busy: boolean; canDelete: boolean; onCreate: (name: string, kind: Home['kind']) => void; onUpdate: (name: string, kind: Home['kind']) => void; onDelete: () => void; onRefresh: () => Promise<void> }) {
  const [name,setName]=useState(home.name),[kind,setKind]=useState<Home['kind']>(home.kind);
  const [newName,setNewName]=useState(''),[newKind,setNewKind]=useState<Home['kind']>('home');
  const owner=!cloud||home.role==='owner';
  useEffect(()=>{setName(home.name);setKind(home.kind);},[home.id,home.name,home.kind]);
  return <><section className="settings-group"><h2>住まいの管理</h2>
    {owner ? <form className="form-grid" onSubmit={e=>{e.preventDefault();if(name.trim())onUpdate(name.trim(),kind);}}><label className="wide"><span>住まいの名前</span><input required maxLength={80} value={name} onChange={e=>setName(e.target.value)} /></label><label><span>種類</span><select value={kind} onChange={e=>setKind(e.target.value as Home['kind'])}>{kinds.map(k=><option key={k.id} value={k.id}>{k.label}</option>)}</select></label><button className="secondary-button" disabled={busy||!name.trim()}>名前・種類を保存</button><button type="button" className="text-button" disabled={busy||!canDelete} onClick={onDelete}>この住まいを削除</button></form> : <p>家族として参加中です。住まいの名前変更と削除は所有者が行えます。</p>}
    <h3>住まいを追加</h3><form className="form-grid" onSubmit={e=>{e.preventDefault();if(newName.trim()){onCreate(newName.trim(),newKind);setNewName('');}}}><label className="wide"><span>新しい住まいの名前</span><input required maxLength={80} value={newName} onChange={e=>setNewName(e.target.value)} placeholder="例：実家" /></label><label><span>新しい住まいの種類</span><select value={newKind} onChange={e=>setNewKind(e.target.value as Home['kind'])}>{kinds.map(k=><option key={k.id} value={k.id}>{k.label}</option>)}</select></label><button className="secondary-button" disabled={busy||!newName.trim()}>住まいを追加</button></form>
  </section>{cloud ? <SharingControls key={home.id} home={home} disabled={busy} onRefresh={onRefresh}/> : <section className="settings-group"><h2>家族と共有</h2><p>クラウド保存にログインすると、住まいごとに家族を招待できます。</p></section>}</>;
}
function SharingControls({home,disabled,onRefresh}:{home:Home;disabled:boolean;onRefresh:()=>Promise<void>}){
 const [code,setCode]=useState(''),[joinCode,setJoinCode]=useState(''),[nickname,setNickname]=useState('');
 const [members,setMembers]=useState<{user_id:string;nickname:string}[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[copyMessage,setCopyMessage]=useState('');
 const client=getSupabase();const owner=home.role==='owner';
 useEffect(()=>{let active=true;if(client)client.from('home_members').select('user_id,nickname').eq('homeId',home.id).then(({data,error})=>{if(active){if(error)setMessage('家族一覧を取得できませんでした。');else setMembers(data??[]);}});return()=>{active=false;};},[client,home.id]);
 const action=async(run:()=>Promise<void>)=>{if(busy||disabled)return;setBusy(true);setMessage('');try{await run();}catch{setMessage('手続きを完了できませんでした。通信状態と権限を確認してください。');}finally{setBusy(false);}};
 if(!client)return null;
 return <section className="settings-group"><h2>家族と共有</h2><p>同じ住まいの製品・予定・完了履歴を家族で確認できます。家族も自分のアカウントでクラウド保存にログインしてください。</p><p>招待する人はコードを作って家族に伝え、招待された人は下の「招待された住まいに参加」にコードと表示名を入力します。</p><p>参加した家族は、この住まいの製品・お手入れ・履歴を追加・編集・削除できます。招待コードは共有したい相手だけに伝えてください。</p>
 {owner&&<><button className="secondary-button" disabled={busy||disabled} onClick={()=>void action(async()=>{const{data,error}=await client.rpc('create_home_invite',{home_id:home.id});if(error)throw error;setCode(data as string);setCopyMessage('');})}>招待コードを作る</button>{code&&<><p>7日間有効・1回限りのコードです。</p><label className="wide"><span>招待コード</span><input readOnly value={code} /></label><button className="secondary-button" disabled={busy||disabled} onClick={async()=>{try{await navigator.clipboard.writeText(code);setCopyMessage("招待コードをコピーしました。共有したい家族にだけ送ってください。");}catch{setCopyMessage("コピーできませんでした。招待コードの欄から選択してコピーしてください。");}}}>招待コードをコピー</button>{copyMessage&&<p role="status">{copyMessage}</p>}</>}<button className="text-button" disabled={busy||disabled} onClick={()=>{if(window.confirm('この住まいの未使用の招待コードをすべて無効にしますか？'))void action(async()=>{const{error}=await client.from('home_invites').update({revoked:true}).eq('homeId',home.id).is('used_at',null);if(error)throw error;setCode('');setMessage('未使用の招待コードを無効にしました。');});}}>未使用の招待を取り消す</button></>}
 <h3>参加している家族</h3>{members.length?members.map(m=><div key={m.user_id}><p>{m.nickname}</p>{owner&&<button className="text-button" disabled={busy||disabled} onClick={()=>{if(window.confirm(`「${m.nickname}」の共有アクセスを解除しますか？`))void action(async()=>{const{data,error}=await client.from('home_members').delete().eq('homeId',home.id).eq('user_id',m.user_id).select('user_id');if(error||!data?.length)throw error??new Error();setMembers(current=>current.filter(member=>member.user_id!==m.user_id));});}}>共有を解除</button>}</div>):<p>参加している家族はまだいません。</p>}
 {!owner&&<button className="text-button" disabled={busy||disabled} onClick={()=>{if(window.confirm('この住まいの共有から退出しますか？記録は所有者のもとに残ります。'))void action(async()=>{const{data:{user},error:authError}=await client.auth.getUser();if(authError||!user)throw authError??new Error();const{error}=await client.from('home_members').delete().eq('homeId',home.id).eq('user_id',user.id);if(error)throw error;await onRefresh();});}}>この住まいから退出</button>}
 <h3>招待された住まいに参加</h3><p>参加後は、画面上部の住まい一覧から家族の住まいを選べます。</p><form className="form-grid" onSubmit={e=>{e.preventDefault();void action(async()=>{const{error}=await client.rpc('accept_home_invite',{invite_code:joinCode.trim(),member_name:nickname.trim()});if(error)throw error;setJoinCode('');await onRefresh();setMessage('共有の住まいに参加しました。上部の住まい一覧から選んでください。');});}}><label className="wide"><span>受け取った招待コード</span><input required pattern="[0-9a-f]{64}" maxLength={64} autoComplete="off" value={joinCode} onChange={e=>setJoinCode(e.target.value)} /></label><label className="wide"><span>家族に表示する名前</span><input required maxLength={80} value={nickname} onChange={e=>setNickname(e.target.value)} /></label><button className="primary-button" disabled={busy||disabled||!nickname.trim()||!/^[0-9a-f]{64}$/.test(joinCode.trim())}>この権限で参加する</button></form>
 {message&&<p role="status">{message}</p>}</section>;
}
